//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.25 at 11:35:32 AM EET 
//


package https.rca_ac_rw.verie.soap_app.courses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.rca_ac_rw.verie.soap_app.courses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.rca_ac_rw.verie.soap_app.courses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewCourseRequestDTO }
     * 
     */
    public NewCourseRequestDTO createNewCourseRequestDTO() {
        return new NewCourseRequestDTO();
    }

    /**
     * Create an instance of {@link GetAllCoursesResponse }
     * 
     */
    public GetAllCoursesResponse createGetAllCoursesResponse() {
        return new GetAllCoursesResponse();
    }

    /**
     * Create an instance of {@link GetAllCoursesRequest }
     * 
     */
    public GetAllCoursesRequest createGetAllCoursesRequest() {
        return new GetAllCoursesRequest();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link NewCourseResponseDTO }
     * 
     */
    public NewCourseResponseDTO createNewCourseResponseDTO() {
        return new NewCourseResponseDTO();
    }

}
